---
- hosts: all
  vars:
    proxify_it: False
  roles:
    - role: '{{ playbook_dir }}'
- hosts: all
  vars:
    proxify_it: True

    # https://proxy-list.org/english/search.php

    http_proxy_scheme: http
    http_proxy_hostname: 3.219.153.200
    http_proxy_port: 80
    http_proxy_host: '{{ http_proxy_hostname }}:{{ http_proxy_port }}'

    https_proxy_scheme: https
    https_proxy_hostname: 3.10.251.232
    https_proxy_port: 80
    https_proxy_host: '{{ https_proxy_hostname }}:{{ https_proxy_port }}'

    no_proxy_hosts: '127.0.0.1,localhost'
    no_proxy_domains_with_dot: '.localdomain'
    no_proxy_domains_with_star: '*.localdomain'
    
    proxy_env:
      http_proxy: '{{ http_proxy_scheme }}://{{ http_proxy_host }}/'
      https_proxy: '{{ https_proxy_scheme }}://{{ https_proxy_host }}/'
      no_proxy: '{{ no_proxy_hosts }},{{ no_proxy_domains_with_dot }},{{ no_proxy_domains_with_star }}'
  roles:
    - role: '{{ playbook_dir }}'
