---
- name: post_proxify_pkg_upgrade
  become: true
  become_user: root
  when: >
    (proxify_config.enable_pkg_upgrade | default(false))
    and proxify_proxy_env is defined
  with_items: '{{ proxify_pkg_update_cmds | default([]) }}'
  command: '{{ item }}'
  environment: '{{ proxify_proxy_env }}'
- name: proxify_rd_shutdown_then_start
  command: bash -lc "rdctl shutdown && rdctl start"
